### ISSUE TITLE
Fleshlight Launch connects but is unreliable on macOS noble

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-js#181]
Launch seems to work fine on Linux after fixing #176. On macOS, it connects, but we get a lot of the following:

```
(node:66440) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 write listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 write listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:246:17)
    at Characteristic.addListener (events.js:262:10)
    at Characteristic.once (events.js:291:8)
    at Characteristic.write (/Users/qdot/code/git-projects/buttplug-js/node_modules/@abandonware/noble/lib/characteristic.js:69:10)
    at Promise (internal/util.js:290:30)
    at new Promise (<anonymous>)
    at bound  (internal/util.js:289:12)
    at ButtplugNodeBluetoothLEDevice.<anonymous> (/Users/qdot/code/git-projects/buttplug-js/packages/buttplug-node-bluetoothle-manager/dist/ButtplugNodeBluetoothLEDevice.js:96:61)
    at Generator.next (<anonymous>)
    at /Users/qdot/code/git-projects/buttplug-js/packages/buttplug-node-bluetoothle-manager/dist/ButtplugNodeBluetoothLEDevice.js:14:71
```

**Comment by qdot** [comment]
buttplug-js will soon be part of buttplug-wasm in https://github.com/buttplugio/buttplug-rs-ffi, closing this bug as it relates to implementation that will be taken care of in buttplug-rs.
