### ISSUE TITLE
When using Node: UnhandledPromiseRejectionWarning: Error: Lovense Edge v36 cannot handle message of type VibrateCmd

### ISSUE THREAD

**Issue by Fedack** [buttplugio/buttplug-js#221]
**Describe the bug**
When using Node with the buttplug-node-bluetoothle-manager when sending a vibrate message to Lovense Edge v32 the server encounters the error below.
A note, I had to add the following line to load the device configurations:
buttplug_1.DeviceConfigurationManager.LoadFromInternalConfig()

This was added in:
node_modules/buttplug-node-bluetoothle-manager/dist/ButtplugNodeBluetoothLEDeviceManager.js

**Expected behavior**
When sending the command to vibrate from the client, the Lovense toys register correctly and vibrates.

**Additional context**
(node:30190) UnhandledPromiseRejectionWarning: Error: Lovense Edge v36 cannot handle message of type VibrateCmd
    at Lovense.<anonymous> (/home/pi/Node/node_modules/buttplug-node-bluetoothle-manager/node_modules/buttplug/dist/main/src/devices/ButtplugDeviceProtocol.js:38:23)
    at Generator.next (<anonymous>)
    at /home/pi/Node/node_modules/buttplug-node-bluetoothle-manager/node_modules/buttplug/dist/main/src/devices/ButtplugDeviceProtocol.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/Node/node_modules/buttplug-node-bluetoothle-manager/node_modules/buttplug/dist/main/src/devices/ButtplugDeviceProtocol.js:11:12)
    at Lovense.ButtplugDeviceProtocol.ParseMessage (/home/pi/Node/node_modules/buttplug-node-bluetoothle-manager/node_modules/buttplug/dist/main/src/devices/ButtplugDeviceProtocol.js:36:39)
    at ButtplugDevice.<anonymous> (/home/pi/Node/node_modules/buttplug-node-bluetoothle-manager/node_modules/buttplug/dist/main/src/devices/ButtplugDevice.js:24:41)
    at Generator.next (<anonymous>)
    at /home/pi/Node/node_modules/buttplug-node-bluetoothle-manager/node_modules/buttplug/dist/main/src/devices/ButtplugDevice.js:15:71
    at new Promise (<anonymous>)
(node:30190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by qdot** [comment]
buttplug-node is basically dead at this point, new node libraries will probably bind to buttplug-rs via Neon.

It was a nightmare to get this working in the first place and a lot of the libraries it depends on (noble, etc) have had to be forked due to attrition, and buttplug-node never even really worked right. Concentration is now on rust.

Marking WONTFIX.

**Comment by qdot** [comment]
(But thanks for the bug report nonetheless)

**Comment by Fedack** [comment]
Understandable, node was a fallback anyway, to rust I go again. Thanks :)
